#### **This is faster than pandas. But pandas is more user-friendly. Numpy is used to organise the given data in arrays and filter it.**

## **Intro to numpy and its functions**

In [1]:
import numpy as np
import time

x = np.random.rand(100000)          # np.random.rand(no. of elements)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[0.63214351 0.75265202 0.81481215 ... 0.53211087 0.73376349 0.72434695]


In [2]:
# 1)
import time

x = np.random.rand(100000)

start = time.time()                       # time.time() --> stores the time taken to start the code
mean = sum(x)/len(x)
print(time.time() - start)

0.005808591842651367


In [ ]:
# 2)
import numpy as np
import time

x = np.random.rand(100000)

start = time.time()
mean_np = np.mean(x)
print(time.time() - start)

0.00055694580078125


#### NOTE: From the above 2 code cells we can the the process to find mean of the numpy arrays (or list of same datatype) is less for numpy when compared to python.

In [3]:
# ndarray: is a n-dimentional array in python which holds same type of datatypes

import numpy as np

x = np.array([[4,3,6,4],[5,32,54,3],[4,47,38,32]])             # converts the list [] to ndarrays
y = np.array([4,3,24,21.5,42])                                 # if different datatypes --> priority order: string > int, float > int (UPCASTING)
z = np.array(["hello","world","destruction"])

print(f"X: {x}")
print(x.size)                                                  # gives total no. of elements in nd
print(x.shape)                                                 # shape of array: size along its each dimension (eg: 3D --> (x,y,z))
print(type(x))                                                 # as by looking at output of ndarray, we cannot determine weather it is list or ndarray. so we use type()
print(x.dtype)                                                 # dtype(): gives the type of elements in x ndarray.

print()

print(f"Y: {y}")
print(y.shape)
print(type(y))
print(y.dtype)                                                  # float64 --> float = represents float datatype, 64 = no. of bits

print()

print(f"Z: {z}")
print(z.shape)
print(type(z))
print(z.dtype)                                   # U11 --> U = represents string , 11 = represents no. of bits taken in memory

X: [[ 4  3  6  4]
 [ 5 32 54  3]
 [ 4 47 38 32]]
12
(3, 4)
<class 'numpy.ndarray'>
int32

Y: [ 4.   3.  24.  21.5 42. ]
(5,)
<class 'numpy.ndarray'>
float64

Z: ['hello' 'world' 'destruction']
(3,)
<class 'numpy.ndarray'>
<U11


In [4]:
import numpy as np

n = np.array([2.5,2.566,24.95], dtype = np.str_)           # Instead of default "upcasting", we can define the dtype.

print(n)
print(n.dtype)

['2.5' '2.566' '24.95']
<U5


#### To save a ndarray "x", we use command **np.save("my_array",x)** which make x ndarray to be saved in a file named my_array.npy.
#### You can load the saved ndarray into a variable by using load() i.e with the command **y = np.load("my_array.npy")**

### **Specialized ndarrays**

In [5]:
import numpy as np

f = np.zeros((3,1))                 # represent --> np.zeros((rows,colomns))   --> gives "float" a it is more precise that int.
o = np.ones((2,3))
p = np.full((3,2),7)                # represent --> np.full((shape=(rows,colomns)),const value)
k = np.eye(3)                       # creates a identity matrix --> diagonal matrix , diagonal elements = 1.
j = np.diag([45,23,85,23])          # creates a diagonal matrix by taking (diagonal elements) as size.

print(f)
print(f.dtype)
print(o)
print(o.dtype)

print()

print(p)
print(p.dtype)
print(k)
print(j)

[[0.]
 [0.]
 [0.]]
float64
[[1. 1. 1.]
 [1. 1. 1.]]
float64

[[7 7]
 [7 7]
 [7 7]]
int32
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[45  0  0  0]
 [ 0 23  0  0]
 [ 0  0 85  0]
 [ 0  0  0 23]]


In [6]:
import numpy as np

# can creates only rank 1 matrix

d = np.arange(10)                           # acts same like range() i.e --> np.arange(start,stop,step)   [NOTE: can take non-integer steps, unlike range()]
f = np.arange(4,12)                         #[LIMITATION: can give till 1 decimal points]
j = np.arange(4,9,0.2)

print(d)
print(f)
print(j)

[0 1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11]
[4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4
 7.6 7.8 8.  8.2 8.4 8.6 8.8]


#### np.linepace(): can make ndarray of floating points with more than 1 decimal points in evenly spaced.closed intervel i.e inclusives "stop" in (start,stop).
#### REASON WHY LINSPACE BETTER THAN ARANGE: Instead of step, we use no. of elements we needed. [AND] (DEFAULT: step: +1, no. of elements: 50)


In [7]:
import numpy as np

l = np.linspace(0,25,10)            # creates **evenly spaced** 10 elements of ndarray

i = np.linspace(0,25,10,endpoint=False)      # we can make the endpoint exclusive too (as originally linspace has inclusive intervals)

print(l)
print(i)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


####Shape of ndarray: (rows,colomns)

####size of ndarray: total no. of elements in ndarray --> rows*colomns

In [8]:
# np.reshape():combined with linspace or arange, we can convert rank 1 ndarray (from linspace or arange) into rank 2 ndarray.

import numpy as np

a = np.arange(30)
a = np.reshape(a,(6,5))                   # syntax --> np.reshape(ndarray,shape)      --> called as function

print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
import numpy as np

a = np.arange(20).reshape(4,5)              #   --> called as method
b = np.linspace(0,30,10).reshape(2,5)

print(a)
print(a.reshape(1,20))                     # instead of [[0 1 2 3 4],[5 6 7 8 9]..], we get [[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15..]] --> therefore, elements are considered,
print(b)                                   # not list of elements ([1,2,3,4]) as 1 in (rows,colomns)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
[[ 0.          3.33333333  6.66666667 10.         13.33333333]
 [16.66666667 20.         23.33333333 26.66666667 30.        ]]


In [9]:
import numpy as np

f = np.random.random((3,3))                   # gives random elements in given shape
j = np.random.randint(4,16,size=(5,5))        # syntax --> np.random.randint(start,stop,size=shape)    => creates random **integer elements** **between limits** in a given shape

print(f)
print(j)

[[0.85296037 0.57167168 0.80517408]
 [0.84472709 0.32842637 0.86833496]
 [0.83641529 0.2273777  0.46433789]]
[[11  5 15  9 13]
 [12 11 12 13  7]
 [13  8 10 12  5]
 [13  6 11 13  4]
 [ 8  7  9 11  5]]


In [10]:
import numpy as np

e = np.random.normal(1,2,size=(1000,1000))              # Syntax: np.random.normal(mean,standard deviation,size=shape)

print(e)

print()

print(e.shape)
print(e.dtype)
print(e.size)
print(e.mean())                 # gives mean value of the whole ndarray
print(e.max())                  # gives max value of the whole ndarray
print(e.min())                  # gives min value of the whole ndarray

print()

print(e<0)
print()
print(e>0)

print()

print((e<0).sum())              # sum of ndarrays elements which are True to condition e<0
print((e>0).sum())              # sum of ndarrays elements which are True to condition e>0


[[ 3.03427959  2.32942211  3.71706487 ...  2.21157903 -0.04376707
   1.95684156]
 [ 1.42817574 -1.75692359  4.78756645 ... -0.27218965  1.18575737
   3.23602817]
 [ 0.21019568  4.63892314  0.57649471 ...  3.05228533 -0.23491892
   2.48569939]
 ...
 [ 1.50799438  1.18410433  3.40218734 ... -0.15363856  4.25349665
   0.91306048]
 [ 1.48052936  0.79549172  2.69350252 ...  0.92535355  2.20901101
   1.83968758]
 [ 0.13427987  0.0828896   1.29112291 ...  0.11697634  3.13207509
   3.23212775]]

(1000, 1000)
float64
1000000
1.0024094746390726
10.429289209845807
-9.54484653118157

[[False False False ... False  True False]
 [False  True False ...  True False False]
 [False False False ... False  True False]
 ...
 [False False False ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]]

[[ True  True  True ...  True False  True]
 [ True False  True ... False  True  True]
 [ True  True  True ...  True False  True]
 ...
 [ True  True  True ..

In [11]:
# **sum()** etc..
import numpy as np

d = np.array([3,-33,87,-88, 82, 28])

print(d<0)                              # gives ndarray of bool which satisfy condition
print((d<0).sum())                      # sums those bools. where, True = 1, False = 0
print(d[d<0])                           # gives the elements itself in the ndarray which satisfy condition d<0
print(d[d<0].sum())                     # sums those elements
print()

print((d<0).mean())
print(d[d<0].mean())

[False  True False  True False False]
2
[-33 -88]
-121

0.3333333333333333
-60.5


In [12]:
import numpy as np

h = np.linspace(2,32,16).reshape(4,4)
i = np.arange(2,33,2).reshape(4,4)

print(h)
print(i)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


### **Accessing & Modifying elements in ndarrays**

In [13]:
import numpy as np

r = np.array([[1,2,3],[4,5,6],[7,8,9]])

r[2,1] = 5                    # --> x[row,colomn]
print(r)

[[1 2 3]
 [4 5 6]
 [7 5 9]]


### **Adding & deleting elements in ndarray (GOAL: MAKE SURE THAT THE SHAPE OF THE NDARRAY IS STABLE)**

####deleting: **np.delete(ndarray,elements,axis)**  --> here axis keyword is not needed for rank 1 ndarray. But for rank 2 ndarray, axis = 0 used to select rows & axis = 1 used to select colomns.

In [15]:
import numpy as np

p = np.array([1,2,3,4,5,6,7])
r = np.array([[1,2,3],[4,5,6],[7,8,9]])

q = np.delete(p,[1,3,6])                         # --> removes 1st and 3rd and 6th index value elements in the ndarray
j = np.delete(r,[1,2],axis=0)                    # --> deletes 1st and 2nd rows(axis=0) in the ndarray
k = np.delete(r,[1],axis=1)                      #  --> deletes 1nd colomn in the ndarray

print(q)
print()
print(j)
print()
print(k)

[1 3 5 6]

[[1 2 3]]

[[1 3]
 [4 6]
 [7 9]]


#### **NOTE: We cannot delete a single element in a rank 2 ndarray because the ndarray will be unstable.We can only delete a whole rows or colomns. If we want a element to be deleted, in place of that element we can keep 0, so that the ndarray structure will not be disturbed. (3/3/3 != 3/2/3)**

In [ ]:
r = np.array([[1,2,3],[4,5,6],[7,8,9]])

r[1,2] = 0
print(r)

[[1 2 3]
 [4 5 0]
 [7 8 9]]


#### NOTE: **Rank 1 ndarray:** 1 dimentional array with 1 argument i.e, rows
#### **Rank 2 ndarray:** 2 dimentional array with 2 arguments i.e, rows,colomns
#### **Rank 3 ndarray :** 3 dimentional arrays with 3 arguments i.e, rows, colomns,thickness/height
#### so on..

#### Adding: **np.append(ndarray,element,axis)** --> Same as delete(), element --> value which need to be appended(i.e, added at the end). For rank 1 ndarray, we append element. But in rank 2 ndarray, we append a whole ndarray/list (As we cannot modify(add/delete) elements inside a sub ndarray)

In [16]:
import numpy as np

p = np.array([1,2,3,4,5,6,7])
r = np.array([[1,2,3],[4,5,6],[7,8,9]])

p = np.append(p,[8,9,10])                         # --> adding a ndarray/list of elements [or] element at the end
z = np.append(r,[[10,11,12]],axis=0)              # --> adding a row at the end
x = np.append(r,[[10],[11],[12]],axis=1)          # --> adding a colomn at the end   => represent reason --> [[10],[11],[12]]  =>[[10],
                                                  #                                                                                [11]
print(p)                                          #                                                                                [12]]
print(z)                                          # therefore to append in the colomn, the ndarray should be in same shape as other --> same as merging 2 arrays in colomn wise
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


#### **np.insert(ndarray,index,elements,axis)** --> can add elements at a specified place in ndarray.

In [17]:
import numpy as np

p = np.array([1,2,4,5,6,7],dtype=float)
r = np.array([[1,2,3],[4,5,6],[7,8,9]])

s = np.insert(p,2,[3,3.5,3.6])                    # --> added a ndarray/list of elements in the 2nd index

h = np.insert(r,2,[5,3,4],axis=0)                 # --> added a row in 2nd index
j = np.insert(r,2,[5],axis=0)                     # **Resizing(advantage)** --> even if we add element "5", it is converted to a row of same size and fits.so, no chance of unstability
k = np.insert(r,2,[[4],[3],[7]],axis=0)           # adds a list of rows in 2nd row [or] **adds elements to row 2 in colomn wise**

a = np.insert(r,3,[0],axis=1)                     # added a list of "0" in 3rd index of colomn
b = np.insert(r,2,[1,5,3],axis=1)                 # added a list of elements in 2nd colomn
c = np.insert(r,2,[[8],[5],[0]],axis=1)           # adds a list of colomns in 2nd colomn [or] **adds elements to colomn in row wise**

print(s)
print()
print(h)
print(j)
print(k)
print()
print(a)
print(b)
print(c)

[1.  2.  3.  3.5 3.6 4.  5.  6.  7. ]

[[1 2 3]
 [4 5 6]
 [5 3 4]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [5 5 5]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [4 4 4]
 [3 3 3]
 [7 7 7]
 [7 8 9]]

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
[[1 2 1 3]
 [4 5 5 6]
 [7 8 3 9]]
[[1 2 8 5 0 3]
 [4 5 8 5 0 6]
 [7 8 8 5 0 9]]


In [18]:
import numpy as np

p = np.array([1,1,1])
r = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a = np.vstack((p,r))
b = np.vstack((r,p))

h = np.hstack((r,p.reshape(3,1)))               # --> to stack p to right of r, we need to reshape p from rows to colomns


print(a)
print(b)
print()
print(h)
print(r.reshape(1,9))

[[1 1 1]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 1 1]]

[[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]
[[1 2 3 4 5 6 7 8 9]]


#### **SUMMARY: delete() --> whole rows/colomns ,append() --> elements in row or colomn pattern to merge in row(size=0) or colomn(size=1) respectively ,insert() --> see in that section, vstack() & hstack() --> just merging.**
#### **reshape(rows,colomns) --> counts elements as 1 entity and counts (rows,colomns).**

### **Slicing of ndarrays**

In [19]:
import numpy as np

x = np.arange(20).reshape(4,5)         # rank 2 array/ 2D array

print(x)
print(x[1:2,1:3])                     # syntax --> x[row_slice,colomn_slice]
print(x[1:3,1:4])
print()
print(x[:,3])                      # gives 1D array
print(x[1,:])                      # gives 1D array
print()
print(x[:,2:3])                    # gives 2D array
print(x[1:3,:])                    # gives 2D array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[6 7]]
[[ 6  7  8]
 [11 12 13]]

[ 3  8 13 18]
[5 6 7 8 9]

[[ 2]
 [ 7]
 [12]
 [17]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
# NOTE: arrays are mutable.
# Proof:
import numpy as np

g = np.arange(20).reshape(4,5)

c = g[1:4,2:5]
c[2,2] = 888

print(g)          # from the result when c is modified, g also modified. so, c is view of g but not copy. like mutable type

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 888]]


### **Boolean Indexing** --> when we have big data, indexing is not possible. so, we condition to find required data

In [21]:
import numpy as np

x = np.arange(25).reshape(5,5)

print(x)
print(x < 10)
print(x[x < 10])
print(x[x < 10].sum())

print()

print(x[(x > 10) & (x < 18)])
x[(x > 10) & (x < 18)] = 0
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[0 1 2 3 4 5 6 7 8 9]
45

[11 12 13 14 15 16 17]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  0  0  0  0]
 [ 0  0  0 18 19]
 [20 21 22 23 24]]


### **Set Operations** --> Useful when comparing ndarrays

In [22]:
import numpy as np

i = np.array([1,2,3,4,5])
j = np.array([6,7,2,8,4])

print(np.union1d(i,j))
print(np.intersect1d(i,j))
print(np.setdiff1d(i,j))

[1 2 3 4 5 6 7 8]
[2 4]
[1 3 5]


In [23]:
import numpy as np

i = np.array([[1,2],[4,5]])
j = np.array([[6,5],[8,6]])

print(i)
print(j)
print()
print(np.setdiff1d(i,j))           # gives difference in a 1D format

[[1 2]
 [4 5]]
[[6 5]
 [8 6]]

[1 2 4]


### **Sorting** --> sorts ndarrays elements in 1D & 2D

In [24]:
import numpy as np

l = np.random.randint(1,11,size=(10,))

print(l)
l.sort()                    # permantly changes the original ndarray. unlike print(sorted(l))
print(l)
print(np.unique(l))         # gives a ndarray without non reapeting elements


[ 9  1  7 10  6  1  7  2 10  3]
[ 1  1  2  3  6  7  7  9 10 10]
[ 1  2  3  6  7  9 10]


In [25]:
import numpy as np

l = np.random.randint(1,11,size=(10,))

print(np.sort(l))           # temporarily sorts the original ndarray and prints
print(l)
print(np.sort(np.unique(l)))           # SHORTCUT SYNTAX

[1 2 3 3 4 6 7 7 7 8]
[7 3 8 1 3 7 7 4 6 2]
[1 2 3 4 6 7 8]


In [26]:
import numpy as np

l = np.random.randint(1,11,size=(5,5))

print(l)
print()
print(np.sort(l,axis=0))           # sorting through rows i.e, in 1st colomn, between 1st, 2nd, 3rd, 4th, 5th row element,which is small to big. like that in 2nd colomn..
print()
print(np.sort(l,axis=1))           # sorting through colomns i.e, in 1st row, between 1st, 2nd, 3rd, 4th, 5th colomn element,which is sall to big. like that in 2nd row..

[[ 8  6  1  7  7]
 [10  1  2  8  5]
 [ 9  4  9 10  3]
 [ 2  6  5  3  5]
 [10  1  2  3  6]]

[[ 2  1  1  3  3]
 [ 8  1  2  3  5]
 [ 9  4  2  7  5]
 [10  6  5  8  6]
 [10  6  9 10  7]]

[[ 1  6  7  7  8]
 [ 1  2  5  8 10]
 [ 3  4  9  9 10]
 [ 2  3  5  5  6]
 [ 1  2  3  6 10]]


In [27]:
import numpy as np

u = np.arange(1,26).reshape(5,5)

print(u[u % 2 != 0])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


###**Arithmetic Operations** --> need to have same shape ndarrays

In [28]:
import numpy as np

u = np.array([1,2,3,4])
i = np.array([6.2,8.4,1.2,4.2])

print(u + i)
print(np.add(u,i))

print(u - i)
print(np.subtract(u,i))

print(u * i)
print(np.multiply(u,i))

print(u / i)
print(np.divide(u,i))

[ 7.2 10.4  4.2  8.2]
[ 7.2 10.4  4.2  8.2]
[-5.2 -6.4  1.8 -0.2]
[-5.2 -6.4  1.8 -0.2]
[ 6.2 16.8  3.6 16.8]
[ 6.2 16.8  3.6 16.8]
[0.16129032 0.23809524 2.5        0.95238095]
[0.16129032 0.23809524 2.5        0.95238095]


In [29]:
import numpy as np

u = np.array([1,2,3,4]).reshape(2,2)
i = np.array([6.5,8.7]).reshape(2,1)

print(u)
print(i)
print(u + i)         # --> 2 x 2 & 2 x 1 => as colomn of one and row of other is same. so, can do operation ==> something should be same.

[[1 2]
 [3 4]]
[[6.5]
 [8.7]]
[[ 7.5  8.5]
 [11.7 12.7]]


In [30]:
# Some mathematical functions in numpy
import numpy as np

u = np.array([1,2,3,4])

print(np.exp(u))
print(np.sqrt(u))
print(np.power(u,5))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.         1.41421356 1.73205081 2.        ]
[   1   32  243 1024]


In [31]:
import numpy as np

i = np.array([[1,2],[4,5]])

print(i.mean())
print(i.mean(axis=0))         # mean of each rows (1st+2nd row,..)
print(i.mean(axis=1))         # mean of each colomn (1st+2nd colomn,..)

print()
print(i.sum())
print(i.sum(axis=0))         # sum of each rows (1st+2nd row,..)
print(i.sum(axis=1))         # sum of each colomn (1st+2nd colomn,..)

print()
print(i.std())
print(i.std(axis=0))         # standard deviation of each rows (1st+2nd row,..)
print(i.std(axis=1))         # standard deviation of each colomn (1st+2nd colomn,..)

print()
print(i.max())
print(i.max(axis=0))        # max of each rows (1st+2nd row,..)
print(i.max(axis=1))        # max of each colomn (1st+2nd colomn,..)

print()
print(i.min())
print(i.min(axis=0))        # min of each rows (1st+2nd row,..)
print(i.min(axis=1))        # min of each colomn (1st+2nd colomn,..)

print()
print(np.median(i))
print(np.median(i,axis=0))  # median of each rows (1st+2nd row,..)
print(np.median(i,axis=1))  # median of each colomn (1st+2nd colomn,..)

3.0
[2.5 3.5]
[1.5 4.5]

12
[5 7]
[3 9]

1.5811388300841898
[1.5 1.5]
[0.5 0.5]

5
[4 5]
[2 5]

1
[1 2]
[1 4]

3.0
[2.5 3.5]
[1.5 4.5]


In [ ]:
import numpy as np

i = np.array([[1,2],[4,5]])

print(i + 5)
print(i * 5)
print(i - 5)
print(i / 5)

[[ 6  7]
 [ 9 10]]
[[ 5 10]
 [20 25]]
[[-4 -3]
 [-1  0]]
[[0.2 0.4]
 [0.8 1. ]]


### **Broadcasting**

In [ ]:
import numpy as np

x = np.array([1,2,3])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

f = x.reshape(3,1)

print(x + y)            # added at the rows
print(f + y)            # added at the colomns

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
